### ISSUE TITLE
Value of commandByte Cannot be Assigned to ev.param1

### ISSUE THREAD

**Issue by Thysbelon** [Thysbelon/midi2sseq#1]
ev.param1 ends up with a different value than commandByte, even though they should be the same.
[Location of bug](https://github.com/Thysbelon/midi2sseq/blob/eeacfa0dd5c1c00c0128bdf846fff52c88163473/source/SSeqConv.cpp#L275).    
Both variables have the same data type.

example:   
commandByte has a value of `0xC4`.     
`ev.param1 = commandByte;`     
The value of ev.param1 should be `0xC4`, instead it is `0x7F`.

**Comment by Thysbelon** [comment]
commandByte holds the same value before and after the statement `ev.param1 = commandByte;`, but `ev.param1` is always `0x7F` when it should be `0xC4`.    

The only exception is that if I assign the value `0xC4` directly to `ev.param1`:
```
ev.param1 = 0xC4;
// or
unsigned long testNum = 0xC4;
ev.param1 = testNum;
```
`ev.param1` is always `0xC4`.

**I need help to fix this issue.**

**Comment by gmottajr** [comment]
Hi @Thysbelon,

I noticed the issue you raised regarding the assignment where `commandByte` (with the value `0xC4`) is being assigned to `ev.param1`, but `ev.param1` ends up with a different value (`0x7F`). Both variables are of the same data type, so this behavior is unexpected.

To help investigate this further and propose a solution, could you provide the following details:

1. **Acceptance Criteria**: What is the expected behavior of the assignment, and what would constitute a successful fix in this case?
2. **Unit Test Details**: Could you share any relevant unit tests, or describe the testing environment, such as the framework in use and how `ev.param1` is being validated after the assignment?

With this additional information, I can better understand the issue and offer a more effective solution.

### Initial Fix Proposition

Based on the description of the issue, where `commandByte` is being assigned to `ev.param1`, but `ev.param1` ends up with a different value (e.g., `0xC4` is assigned, but `0x7F` is the result), here are some initial ideas for investigation and potential fixes:

#### 1. Data Type Mismatch
Although it is mentioned that both `commandByte` and `ev.param1` have the same data type, there might be an implicit type conversion or sign extension happening, especially if one variable is signed and the other unsigned.

- **Action**: Check that both variables have the same type. If one is signed and the other is unsigned, this could lead to unexpected behavior. Using `uint8_t` for byte values would be ideal. How does that sound? 
  
  **Example Fix** (if types are mismatched):
  ```cpp
  uint8_t commandByte = 0xC4;
  ev.param1 = static_cast<uint8_t>(commandByte); // Ensure assignment to the correct type

Let me know your thoughts.
Best regards,  
Jr.

**Comment by Thysbelon** [comment]
Thank you for your response @gmottajr .

ev.param1 and commandByte should both be uint8_t. `ev.param1` is defined as `uchar` in [SSeqConv.h line 65](https://github.com/Thysbelon/midi2sseq/blob/eeacfa0dd5c1c00c0128bdf846fff52c88163473/source/SSeqConv.h#L65); `uchar` is defined as `uint8_t` in [endian.h line 15](https://github.com/Thysbelon/midi2sseq/blob/eeacfa0dd5c1c00c0128bdf846fff52c88163473/source/endian.h#L15)

Using `static_cast` did not resolve the issue.

Here is what I do to test this program:

In my Ubuntu terminal:

- `make`
- `./midi2sseq sseqcomtest6.mid sseqcomtest6.mid.sseq`
- View the command line output

I have just updated the code to include more print statements.

Here is the relevant part of the code (lines 258-282):

```c
if (stringMarker.substr(0, 7) == "Random:"){
	std::string valString=stringMarker.substr(7);
	size_t commaPos;
	
	commaPos=valString.find(",");
	const uint8_t commandByte=static_cast<uint8_t>(std::stoul(valString.substr(0, commaPos), nullptr, 16));
	valString.erase(0,commaPos + 1);
	commaPos=valString.find(",");
	int16_t randMin=std::stoi(valString.substr(0, commaPos));
	valString.erase(0,commaPos + 1);
	int16_t randMax=std::stoi(valString);
	
	ev.cmd=CNV_RANDOM;
	printf("commandByte: 0x%X\n", commandByte);
	printf("\"commandByte == 0xC4\" bool: %d\n", commandByte == static_cast<uint8_t>(0xC4));
	printf("\"commandByte == 0b11000100\" bool: %d\n", commandByte == static_cast<uint8_t>(0b11000100));
	printf("ev.param1 (before assignment): 0x%X\n", ev.param1);
	ev.param1 = static_cast<uint8_t>(commandByte); // BUG: why does the value change from C4 to 7F even though I'm not changing it?
	ev.paramwide=(ushort)randMin;
	ev.paramwide2=(ushort)randMax;
	//unsigned long testNum = 0xC4;
	//ev.param1 = testNum;
	
	printf("random: commandByte: 0x%X, randMin: %d, randMax: %d. i: %d\n", commandByte, randMin, randMax, i);
	printf("random: ev.param1: 0x%X, ev.paramwide: %d, ev.paramwide2: %d. i: %d\n", ev.param1, (int16_t)ev.paramwide, (int16_t)ev.paramwide2, i);
}
```

Here is the relevant part of the command line output, which shows the bug:

```
commandByte: 0xC4
"commandByte == 0xC4" bool: 1
"commandByte == 0b11000100" bool: 1
ev.param1 (before assignment): 0x2B
random: commandByte: 0xC4, randMin: -127, randMax: 127. i: 1
random: ev.param1: 0x7F, ev.paramwide: 127, ev.paramwide2: 127. i: 1
```

Best regards,
Thysbelon

**Comment by gmottajr** [comment]
I needed to setup an env in order to address this issue. Would you assign that to me, please? I will complete as soon as I have my env ready. Let you know asap.

**Comment by Thysbelon** [comment]
[I fixed the issue](https://github.com/Thysbelon/midi2sseq/commit/758e4cdb24513462bd4e3dcb464702b948bb0535). The cause was that ev.param1, ev.paramwide and ev.paramwide2 were all part of the same union, so only one of these variables at a time could hold a value. I fixed it by altering SSeqConv.h to make it so they were no longer part of a union.

Thank you for your help.

**Comment by gmottajr** [comment]
Hi @Thysbelon, I am sorry. I apologize, I had problems here with my environment. I m fishing to set up it just now.
So I could not address this matter.
Thanks for the update! I’m glad to hear you found the root cause and resolved the issue. The union explanation makes perfect sense, and separating the variables in SSeqConv.h sounds like the right approach to avoid overwriting values.
Appreciate you circling back on this, I’ll keep that in mind for future debugging. Let me know if you need any further testing or if there’s anything else I can help with!

Best regards,
Jr.
